"""Markdown report and handoff document generation."""

from __future__ import annotations

from pathlib import Path
from typing import Any


def _fmt_counts(mapping: dict[str, Any]) -> str:
    return ", ".join(f"{key}: {value}" for key, value in mapping.items())


def build_preprocessing_report(payload: dict[str, Any]) -> str:
    """Build a concise but complete preprocessing report."""

    warnings = payload.get("warnings", [])
    lines = [
        "# Preprocessing Report",
        "",
        "## Raw Files",
        f"- Jigsaw: `{payload['raw_files']['jigsaw']}`",
        f"- Civil Comments: `{payload['raw_files']['civil_comments']}`",
        "",
        "## Schema Mapping Decisions",
    ]
    for source, schema in payload["schema"].items():
        lines.append(f"- {source}: text=`{schema.get('text_column')}`, labels=`{schema.get('label_columns', schema.get('label_column'))}`")
    lines.extend(
        [
            "",
            "## Cleaning Rules",
            "- Unicode NFKC normalization, HTML entity cleanup, line-break replacement, whitespace collapse, and stripping.",
            "- URLs and emails are replaced with stable placeholders.",
            "- No stemming, lemmatization, stopword removal, profanity masking, spelling correction, or aggressive punctuation stripping.",
            "",
            "## Duplicate Removal Summary",
        ]
    )
    for source, summary in payload["duplicate_removal"].items():
        lines.append(
            f"- {source}: input={summary['input_rows']}, removed_missing_text={summary['removed_missing_text']}, "
            f"removed_missing_labels={summary['removed_missing_labels']}, "
            f"removed_normalized_duplicates={summary['removed_normalized_duplicates']}, output={summary['output_rows']}"
        )
    lines.extend(["", "## Split Sizes"])
    for source, summary in payload["split_summary"].items():
        lines.append(
            f"- {source}: method={summary.get('method')}, "
            f"stratify_column={summary.get('stratify_column')}, "
            f"counts={_fmt_counts(summary.get('counts', {}))}"
        )
    jigsaw_counts = payload["split_summary"].get("jigsaw", {}).get("counts", {})
    lines.extend(
        [
            "",
            "## Teammate-Facing Exports",
            f"- `data/processed/train.csv`: {jigsaw_counts.get('train')} rows, columns=`raw_text`, `clean_text`, `label`",
            f"- `data/processed/val.csv`: {jigsaw_counts.get('val')} rows, columns=`raw_text`, `clean_text`, `label`",
            f"- `data/processed/test.csv`: {jigsaw_counts.get('test')} rows, columns=`raw_text`, `clean_text`, `label`",
        ]
    )
    lines.extend(["", "## Label Distributions"])
    for source, validation in payload["validation"].items():
        overall = validation.get("class_distribution_overall", {})
        lines.append(f"- {source}: {overall}")
    lines.extend(["", "## Token Length Statistics"])
    for source, validation in payload["validation"].items():
        token_stats = validation.get("distilbert_token_length_diagnostics", {})
        lines.append(f"- {source}: {token_stats}")
    lines.extend(["", "## Leakage Checks"])
    for source, validation in payload["validation"].items():
        lines.append(f"- {source} raw overlap: {validation.get('raw_hash_overlap_across_splits')}")
        lines.append(f"- {source} normalized overlap: {validation.get('normalized_hash_overlap_across_splits')}")
    if payload.get("civil_aug_external_overlap"):
        lines.append(f"- Civil aug/external overlap: {payload['civil_aug_external_overlap']}")
    lines.extend(["", "## Slice Summaries"])
    for source, summary in payload["slice_summary"].items():
        lines.append(f"- {source}: {summary}")
    lines.extend(
        [
            "",
            "## Assumptions",
            "- Jigsaw is the only dataset for the main non-extension experiment.",
            "- Civil Comments artifacts are optional extension outputs and may be dropped without breaking the Jigsaw pipeline.",
            "- Jigsaw `identity_hate` is treated as an original toxicity label, not as a dataset-provided identity mention column.",
            "- Length buckets use empirical Jigsaw word-length quantiles and are then reused for Civil Comments for comparability.",
            "",
            "## Warnings",
        ]
    )
    if warnings:
        lines.extend(f"- {warning}" for warning in warnings)
    else:
        lines.append("- None.")
    return "\n".join(lines) + "\n"


def build_data_dictionary() -> str:
    """Describe the standardized processed columns."""

    rows = [
        ("sample_id", "Deterministic row identifier generated by source and retained row order."),
        ("source_dataset", "`jigsaw` or `civil_comments`."),
        ("raw_text", "Closest available original comment text; not lowercased."),
        ("text_clean", "Lightly normalized text for transformer models such as DistilBERT."),
        ("text_tfidf", "Lowercased lexical view for TF-IDF + Logistic Regression; punctuation retained."),
        ("clean_text", "Simplified teammate-facing CSV text column derived from `text_clean`."),
        ("binary_label", "Unified toxic vs non-toxic label where 1 means toxic."),
        ("label", "Simplified teammate-facing CSV target column derived from `binary_label`."),
        ("orig_label_info", "Compact JSON string preserving source labels or scores."),
        ("char_len", "Character length of `text_clean`."),
        ("word_len", "Whitespace token count of `text_clean`."),
        ("text_hash_raw", "SHA-256 hash of `raw_text`."),
        ("text_hash_normalized", "SHA-256 hash of duplicate-normalized text."),
        ("bert_token_len", "DistilBERT tokenizer length including special tokens."),
        ("split", "Split assignment."),
        ("has_identity_term", "Reusable identity challenge-slice flag."),
        ("has_obfuscation", "Reusable obfuscation challenge-slice flag."),
        ("implicit_proxy", "Proxy flag for toxic rows without explicit lexicon terms; not a gold label."),
        ("length_bucket", "`short`, `medium`, or `long` from saved thresholds."),
    ]
    lines = ["# Data Dictionary", "", "| Column | Description |", "| --- | --- |"]
    lines.extend(f"| `{name}` | {description} |" for name, description in rows)
    return "\n".join(lines) + "\n"


def build_readme_preprocessing() -> str:
    """Build team handoff documentation."""

    return (
        "# Preprocessing Handoff\n\n"
        "## Main Experiment Files\n"
        "Use only the Jigsaw processed files for the non-extension phase:\n\n"
        "- `data/processed/train.csv`\n"
        "- `data/processed/val.csv`\n"
        "- `data/processed/test.csv`\n"
        "- `data/processed/jigsaw_train.parquet` or `.csv`\n"
        "- `data/processed/jigsaw_val.parquet` or `.csv`\n"
        "- `data/processed/jigsaw_test.parquet` or `.csv`\n\n"
        "The Jigsaw train/validation/test splits are generated with stratification on `binary_label`.\n\n"
        "Civil Comments is optional and is not used in the main experiment.\n\n"
        "## Modeling Columns\n"
        "- Teammate-facing CSVs contain exactly `raw_text`, `clean_text`, and `label`.\n"
        "- TF-IDF + Logistic Regression should use `text_tfidf`.\n"
        "- DistilBERT should use `text_clean`.\n"
        "- The binary target is `binary_label`.\n\n"
        "## Optional Civil Extension Artifacts\n"
        "When Civil Comments is enabled and present, the following files are reserved for controlled augmentation, robustness analysis, or optional external evaluation:\n\n"
        "- `data/processed/civil_aug_pool_full.parquet`\n"
        "- `data/processed/civil_external_test.parquet`\n"
        "- `data/processed/civil_aug_pool_capped_match_jigsaw_train.parquet`\n"
        "- `data/processed/civil_aug_pool_identity.parquet` when identity rows are available\n\n"
        "These files may be dropped without affecting the Jigsaw-only pipeline.\n\n"
        "## Rerun Command\n"
        "From the repository root, run:\n\n"
        "```bash\n"
        "python -m src.preprocessing.pipeline\n"
        "```\n\n"
        "Use the Python environment where `requirements.txt` was installed. On this machine, "
        "`/Users/zhengpeixian/miniforge3/bin/python -m src.preprocessing.pipeline` is the verified interpreter.\n\n"
        "Install runtime dependencies first if needed:\n\n"
        "```bash\n"
        "pip install -r requirements.txt\n"
        "```\n"
    )


def write_markdown(path: Path, content: str) -> None:
    """Write UTF-8 markdown."""

    path.write_text(content, encoding="utf-8")
